(() => {
  const main=document.getElementById('main');let data,filter='todas';const selected={};
  function normalize(json){const preguntas=Array.isArray(json)?json:json.preguntas||[];return{titulo:json.titulo||'Test Bloque 6 STS',bloque:json.bloque||'Meteorologia | Syllabus STS paginas 8-10 | Estado VALIDADO',total:json.total||preguntas.length,preguntas}}
  function stats(){return data.preguntas.reduce((a,q)=>{a[q.dificultad]=(a[q.dificultad]||0)+1;return a},{})}
  function visibleQuestions(){return filter==='todas'?data.preguntas:data.preguntas.filter(q=>q.dificultad===filter)}
  function render(){const count=stats(),visible=visibleQuestions();main.innerHTML=`<section class="panel hero"><h1>${data.titulo}</h1><p>${data.bloque}</p><div class="stats"><span class="pill">${data.total} preguntas</span><span class="pill">${count.facil||0} faciles</span><span class="pill">${count.media||0} medias</span><span class="pill">${count.dificil||0} dificiles</span></div></section><section id="resultado" class="panel result">Selecciona respuestas y pulsa Corregir.</section>${visible.map((q,i)=>`<section class="panel question" data-id="${q.id}"><div class="meta"><span class="tag">${q.id}</span><span class="tag">${q.dificultad}</span><span class="tag">${q.tema}</span></div><h2>${i+1}. ${q.pregunta}</h2><div class="opts">${q.respuestas.map((a,j)=>`<button class="opt" data-id="${q.id}" data-answer="${j}">${a}</button>`).join('')}</div><div class="feedback"><p><b>Explicacion:</b> ${q.explicacion}</p><p><b>Error habitual:</b> ${q.error_habitual}</p><p><b>Referencia:</b> ${q.referencia_concepto||'Syllabus STS paginas 8-10 | Estado VALIDADO'}</p></div></section>`).join('')}`;document.querySelectorAll('.opt').forEach(o=>{const id=o.dataset.id;if(selected[id]===+o.dataset.answer)o.classList.add('selected');o.onclick=()=>{document.querySelectorAll(`.opt[data-id="${id}"]`).forEach(x=>x.classList.remove('selected'));o.classList.add('selected');selected[id]=+o.dataset.answer;};});document.querySelectorAll('nav button[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));}
  function correct(){let score=0;const visible=visibleQuestions();visible.forEach(q=>{const section=document.querySelector(`.question[data-id="${q.id}"]`);section.querySelector('.feedback').classList.add('show');section.querySelectorAll('.opt').forEach(o=>{const v=+o.dataset.answer;o.classList.remove('correct','wrong');if(v===q.respuesta_correcta)o.classList.add('correct');else if(selected[q.id]===v)o.classList.add('wrong');});if(selected[q.id]===q.respuesta_correcta)score++;});document.getElementById('resultado').textContent=`Resultado: ${score} / ${visible.length}`;}
  document.querySelectorAll('nav button[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.getElementById('corregir').onclick=correct;document.getElementById('reiniciar').onclick=()=>{Object.keys(selected).forEach(k=>delete selected[k]);render()};document.getElementById('print').onclick=()=>window.print();fetch('test.json').then(r=>r.json()).then(json=>{data=normalize(json);render()}).catch(()=>{main.innerHTML='<section class="panel">No se pudo cargar el test. Abre esta vista desde Live Server.</section>';});
})();
