(() => {
  const data = window.DRONLAB_BLOQUE, nav = document.getElementById('nav'), content = document.getElementById('content');
  const notesKey = 'dronlab_sts_bloque7_profesor_notes';
  const esc = v => String(v ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const list = a => `<ul>${a.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`;
  function renderNav(active){nav.innerHTML=`<h2>Bloque 7</h2>${data.pantallas.map(i=>`<button class="navbtn ${i.id===active?'active':''}" data-id="${esc(i.id)}">${esc(i.titulo)}</button>`).join('')}`;nav.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>render(b.dataset.id));}
  function render(id=data.pantallas[0].id){const item=data.pantallas.find(s=>s.id===id)||data.pantallas[0];renderNav(item.id);const comp=item.id==='b7-10'?'<article class="box comp"><h3>Complementario separado</h3><p>MME8/geocaging y masas STS-ES nacionales mantienen trazabilidad propia y no se presentan como pagina 11 del Syllabus AESA.</p></article>':'';content.innerHTML=`<section class="card hero"><p class="eyebrow">PROFESOR | BLOQUE 7</p><h1>${esc(item.titulo)}</h1><p>Trazabilidad AESA Syllabus STS pagina ${esc(data.meta.paginas_relacionadas)} | Estado ${esc(data.meta.estado)}.</p></section><section class="grid"><article class="box"><h3>Contenido de pantalla</h3><p>${esc(item.contenido)}</p></article><article class="box script"><h3>Guion docente</h3><p>${esc(item.docente)}</p></article><article class="box"><h3>Preguntas de control</h3>${list(['La carga util esta dentro de MTOM?', 'Que ocurre si el CG sale de limites?', 'Que eje corresponde a cabeceo, alabeo o guinada?', 'Es contenido AESA pagina 11 o complementario separado?'])}</article><article class="box"><h3>Respuestas esperadas</h3>${list(['MTOM incluye aeronave, bateria y carga util.', 'CG fuera de limites causa inestabilidad, incontrolabilidad y fatiga prematura.', 'Alabeo longitudinal, cabeceo lateral y guinada vertical.', 'MME8 y masas STS-ES son complementario separado.'])}</article>${comp}</section><section class="card"><h2>Notas locales</h2><textarea id="notes" class="notes"></textarea></section>`;const notes=document.getElementById('notes'),key=`${notesKey}_${item.id}`;notes.value=localStorage.getItem(key)||'';notes.oninput=()=>localStorage.setItem(key,notes.value);}
  render();
})();
