(() => {
  const main=document.getElementById('main');let data,current=[],filter='todas';
  function normalize(json){const cards=Array.isArray(json)?json:json.flashcards||[];return{titulo:json.titulo||'Flashcards Bloque 8 STS',bloque:json.bloque||'Mitigaciones tecnicas y operacionales del riesgo en tierra | Syllabus STS paginas 11-12 | Estado VALIDADO',total:json.total||cards.length,flashcards:cards}}
  function stats(cards){return cards.reduce((a,c)=>{a[c.dificultad]=(a[c.dificultad]||0)+1;return a},{})}
  function cardHtml(c,i){const mnemonic=c.regla_mnemotecnica?`<p class="small"><b>Regla mnemotecnica</b>${c.regla_mnemotecnica}</p>`:'';return`<article class="flash" tabindex="0" aria-label="${c.id}"><div class="inner"><div class="face front"><div class="meta"><span class="tag">${c.id}</span><span class="tag">${c.dificultad}</span><span class="tag">${c.tipo}</span></div><p class="small"><b>${c.tema}</b>${c.subtema}</p><div class="question">${i+1}. ${c.pregunta}</div></div><div class="face back"><div class="answer">${c.respuesta}</div><p class="small"><b>Explicacion breve</b>${c.explicacion_breve}</p><p class="small"><b>Error habitual</b>${c.error_habitual}</p>${mnemonic}</div></div></article>`}
  function fitCards(){document.querySelectorAll('.flash').forEach(card=>{const inner=card.querySelector('.inner'),faces=[...card.querySelectorAll('.face')];if(!inner)return;inner.style.minHeight='';card.style.minHeight='';const h=Math.max(270,...faces.map(f=>f.scrollHeight+4));inner.style.minHeight=`${h}px`;card.style.minHeight=`${h}px`;});}
  function render(){const visible=filter==='todas'?current:current.filter(c=>c.dificultad===filter),s=stats(data.flashcards);main.innerHTML=`<section class="panel hero"><h1>${data.titulo}</h1><p>${data.bloque}</p><div class="stats"><span class="pill">${data.total} tarjetas</span><span class="pill">${s.facil||0} faciles</span><span class="pill">${s.media||0} medias</span><span class="pill">${s.dificil||0} dificiles</span></div></section><section class="flashgrid">${visible.map(cardHtml).join('')}</section>`;document.querySelectorAll('.flash').forEach(card=>{card.onclick=()=>card.classList.toggle('flipped');card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.classList.toggle('flipped')}}});document.querySelectorAll('nav button[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));fitCards();}
  document.querySelectorAll('nav button[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.getElementById('shuffle').onclick=()=>{current=[...current].sort(()=>Math.random()-.5);render()};document.getElementById('print').onclick=()=>window.print();window.addEventListener('resize',fitCards);fetch('flashcards.json').then(r=>r.json()).then(json=>{data=normalize(json);current=[...data.flashcards];render()}).catch(()=>{main.innerHTML='<section class="panel">No se pudieron cargar las flashcards. Abre esta vista desde Live Server.</section>';});
})();

