(() => {
  const data = window.DRONLAB_BLOQUE, nav = document.getElementById('nav'), content = document.getElementById('content');
  const notesKey = 'dronlab_sts_bloque8_profesor_notes';
  const esc = v => String(v ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const list = a => `<ul>${a.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`;
  function renderNav(active){nav.innerHTML=`<h2>Bloque 8</h2>${data.pantallas.map(i=>`<button class="navbtn ${i.id===active?'active':''}" data-id="${esc(i.id)}">${esc(i.titulo)}</button>`).join('')}`;nav.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>render(b.dataset.id));}
  function render(id=data.pantallas[0].id){const item=data.pantallas.find(s=>s.id===id)||data.pantallas[0];renderNav(item.id);const comp=item.id==='b8-10'?'<article class="box comp"><h3>Complementario separado</h3><p>Resolucion 10/11/2024 y RD 517/2024 mantienen trazabilidad propia y no se presentan como paginas 11-12 del Syllabus AESA.</p></article>':'';content.innerHTML=`<section class="card hero"><p class="eyebrow">PROFESOR | Bloque 8</p><h1>${esc(item.titulo)}</h1><p>Trazabilidad AESA Syllabus STS pagina ${esc(data.meta.paginas_relacionadas)} | Estado ${esc(data.meta.estado)}.</p></section><section class="grid"><article class="box"><h3>Contenido de pantalla</h3><p>${esc(item.contenido)}</p></article><article class="box script"><h3>Guion docente</h3><p>${esc(item.docente)}</p></article><article class="box"><h3>Preguntas de control</h3>${list(['Que personas puede haber en una zona terrestre controlada?', 'Que fases STS-02 deben mantenerse en VLOS?', 'Que funcion tiene el FTS en tierra?', 'Es contenido AESA paginas 11-12 o complementario separado?'])}</article><article class="box"><h3>Respuestas esperadas</h3>${list(['Solo personas participantes y ninguna concentracion de personas.', 'Despegue y aterrizaje, aunque el crucero sea BVLOS.', 'Contener el UAS dentro del perimetro seguro ante perdida de mando.', 'Obstaculos, intrusion, STS-ES-02NE y luz verde nocturna son complementario separado.'])}</article>${comp}</section><section class="card"><h2>Notas locales</h2><textarea id="notes" class="notes"></textarea></section>`;const notes=document.getElementById('notes'),key=`${notesKey}_${item.id}`;notes.value=localStorage.getItem(key)||'';notes.oninput=()=>localStorage.setItem(key,notes.value);}
  render();
})();


